In [ ]:
import numpy as np

x = [0, 0, 0]

y = [[1],
     [1],
     [1],
     [1]]

z = [[1, 1],
     [1, 1],
     [1, 1],
     [1, 1]]

# convert to numpy arrays
x = np.array(x) 
y = np.array(y)
z = np.array(z)

# check valid operations
a = x + y
print("a:", a)
b = z + y
print("b:", b)
# c = x + z # not valid, shapes do not align
# d = np.matmul((x+y), y) # not valid, x+y is a 1D array and y is 2D

"""In NumPy, broadcasting is a powerful mechanism that allows arithmetic operations to be performed on arrays with different shapes.
This is done by conceptually "stretching" the smaller array to match the shape of the larger array, without actually copying the data."""

a: [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
b: [[2 2]
 [2 2]
 [2 2]
 [2 2]]


In [ ]:
import torch

# x, w are rank-one tensors of the same dimension
x = torch.tensor([0.0, 0.0, 0.0], requires_grad=False)
w = torch.tensor([1.0, 1.0, 1.0], requires_grad=True)

# b is rank-zero tensor
b = torch.tensor(1.0)

z = torch.matmul(w,x) + b
y = z * z
y.backward()

w_grad = 2 * (torch.matmul(w, x) + b) * x

The input image size is (28, 28, 3) (colored image with RGB channel), and there is a convolutional layer with 8 filters whose kernel size is (3, 3) with no bias. What is the total number of weight parameters in the convolutional layer?

3 x 3 x 3 x 8 

The number of parameters does not depend on input width and height, but only on the number of input channels.