In [3]:
import torch

In [5]:
def ReLU(tensor):
    """
    Applies the ReLU activation function to the input tensor.
    
    Parameters:
    tensor (torch.Tensor): The input tensor to apply ReLU to.
    
    Returns:
    torch.Tensor: The tensor after applying ReLU.
    """
    return torch.clamp(tensor, min=0.0)

In [6]:
# test your result
a = torch.tensor([[1, 2, -3], [2.5, -0.2, 6]])
ReLU(a)
"""Expected output:
tensor([[1.0000, 2.0000, 0.0000],
        [2.5000, 0.0000, 6.0000]])"""

'Expected output:\ntensor([[1.0000, 2.0000, 0.0000],\n        [2.5000, 0.0000, 6.0000]])'

In [8]:
# Version del copilot
def softmax(tensor):
    """
    Applies the softmax function to the input tensor.
    
    Parameters:
    tensor (torch.Tensor): The input tensor to apply softmax to.
    
    Returns:
    torch.Tensor: The tensor after applying softmax.
    """
    exp_tensor = torch.exp(tensor - torch.max(tensor, dim=-1, keepdim=True).values)
    return exp_tensor / exp_tensor.sum(dim=-1, keepdim=True)

In [10]:
# Test your result
a = torch.tensor([0.6, 5.2, 9.2])
softmax(a)
#Then, the function should return the following as output:
#tensor([1.8076e-04, 1.7983e-02, 9.8184e-01])

tensor([1.8076e-04, 1.7983e-02, 9.8184e-01])

In [ ]:
# Version Mia
def softmax(array):
    ###
    output = torch.exp(array)/(torch.sum(torch.exp(array)))
    return output
    ###

In [12]:
# Test your result
a = torch.tensor([0.6, 5.2, 9.2])
softmax(a)
#Then, the function should return the following as output:
#tensor([1.8076e-04, 1.7983e-02, 9.8184e-01])

tensor([1.8076e-04, 1.7983e-02, 9.8184e-01])

In [13]:
def neural_network_neurons(W, B, X):
    
    ###
    Y = torch.matmul(W,X) + B
    return Y
    ###

In [14]:
# test your code
W = torch.tensor([[1.2, 0.3, 0.1], [.01, 2.1, 0.7]])
B = torch.tensor([2.1, 0.89])
X = torch.tensor([0.3, 6.8, 0.59])

neural_network_neurons(W, B, X)

# Function should return:
# tensor([ 4.5590, 15.5860])

tensor([ 4.5590, 15.5860])